services:
  core:
    build:
      context: .
      dockerfile: ./core/Dockerfile
    container_name: sweet-core
    command: npm run dev
    volumes:
      - ./core:/app
      - ./containers:/app/containers
      - /sys:/sys
      - /dev:/dev
      - /app/node_modules
    env_file:
      - ./core/.env
    restart: always
    ports:
      - "4000:4000"
    privileged: true
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    networks:
      - sweetnet

  web:
    build: ./web
    container_name: sweet-web
    command: npm run dev
    volumes:
      - ./web:/app
      - /app/node_modules
    env_file:
      - ./web/.env.local
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - core
    networks:
      - sweetnet

  audio:
    build:
      context: ./containers/audio
      args:
        NODE_ENV: development
    container_name: sweet-audio
    command: npm run dev
    network_mode: host
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_COOKIE=/run/user/1000/pulse/cookie
    volumes:
      - ./containers/audio:/app
      - /app/node_modules
      - /run/user/1000/pulse:/run/user/1000/pulse
    env_file:
      - ./web/.env.local
    restart: always
    depends_on:
      - core

networks:
  sweetnet:
    driver: bridge
